[package]
name = "nelius"
version = "0.1.0"
edition = "2021"
default-run = "nelius"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
tracing-subscriber.workspace = true
axum = "0.7.5"