[workspace]
resolver = "2"
members = [ "crates/*","nelius"]


[workspace.package]
edition = "2021"
version = "0.0.1"
repository = "https://github.com/centlax/nelius"


[workspace.dependencies]
toml = "0.8.19"